/**
 * GitHub Comment export
 */

import type { BuildReport } from '../types';
import { formatBytes } from '../types';

export function toGitHubComment(report: BuildReport): string {
  const lines: string[] = [];
  const hasFailures = report.violations.length > 0 ||
    report.ruleAlerts.some((r) => r.rule.severity === 'fail');

  if (hasFailures) {
    lines.push('## ❌ Build Guardian — Issues Detected');
  } else if (report.alerts.length > 0) {
    lines.push('## ⚠️ Build Guardian — Warnings');
  } else {
    lines.push('## ✅ Build Guardian — All Clear');
  }
  lines.push('');

  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| **Entries** | ${report.totalEntries} |`);
  lines.push(`| **Build Time** | ${formatDuration(report.totalBuildTimeMs)} |`);
  lines.push(`| **Total Size** | ${formatBytes(report.totalSizeBytes)} |`);
  lines.push(`| **Alerts** | ${report.alerts.length} |`);
  lines.push(`| **Violations** | ${report.violations.length} |`);
  lines.push('');

  if (report.alerts.length > 0) {
    if (report.alerts.length > 5) {
      lines.push('<details>');
      lines.push(`<summary>⚠️ Bloat Alerts (${report.alerts.length})</summary>`);
      lines.push('');
    } else {
      lines.push('### ⚠️ Bloat Alerts');
      lines.push('');
    }

    for (const alert of report.alerts) {
      const pct = `${Math.round(alert.growthPercent * 100)}%`;
      const icon = alert.severity === 'critical' ? '🔴' : '🟡';
      lines.push(`- ${icon} \`${alert.entry}\`: ${formatBytes(alert.previousSizeBytes)} → ${formatBytes(alert.currentSizeBytes)} (**+${pct}**)`);
    }

    if (report.alerts.length > 5) {
      lines.push('');
      lines.push('</details>');
    }
    lines.push('');
  }

  if (report.violations.length > 0) {
    lines.push('### 🚫 Budget Violations');
    lines.push('');
    for (const v of report.violations) {
      lines.push(`- \`${v.entry}\`: ${v.reason}`);
    }
    lines.push('');
  }

  if (report.ruleAlerts.length > 0) {
    lines.push('### 🚨 Rule Alerts');
    lines.push('');
    for (const ra of report.ruleAlerts) {
      const icon = ra.rule.severity === 'fail' ? '❌' : ra.rule.severity === 'critical' ? '🔴' : '🟡';
      lines.push(`- ${icon} **${ra.rule.name}**: ${ra.message}`);
    }
    lines.push('');
  }

  const growing = report.trends.filter((t) => t.direction === 'growing');
  if (growing.length > 0) {
    lines.push('<details>');
    lines.push(`<summary>📈 Growing Trends (${growing.length})</summary>`);
    lines.push('');
    for (const t of growing) {
      lines.push(`- \`${t.entry}\`: ${t.summary}`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('<details>');
  lines.push('<summary>📊 Per-Entry Breakdown</summary>');
  lines.push('');
  lines.push('| Entry | Size | Build Time |');
  lines.push('|-------|-----:|----------:|');
  for (const m of [...report.entryMetrics].sort((a, b) => b.sizeBytes - a.sizeBytes)) {
    lines.push(`| \`${m.entry}\` | ${formatBytes(m.sizeBytes)} | ${formatDuration(m.buildTimeMs)} |`);
  }
  lines.push('');
  lines.push('</details>');
  lines.push('');

  lines.push('<sub>Generated by [@superinstance/build-guardian](https://github.com/SuperInstance/build-guardian) v0.2.0</sub>');

  return lines.join('\n');
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}
