/**
 * GitHub Action — CI integration example.
 *
 * This file shows how to use BuildGuardian in a GitHub Actions workflow.
 * See .github/workflows/ci.yml for the actual workflow definition.
 *
 * Usage in a GitHub Action step:
 *
 *   - name: Build Guardian Check
 *     run: npx ts-node scripts/build-guardian.ts
 *     env:
 *       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 *       GITHUB_EVENT_NAME: ${{ github.event_name }}
 *       GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
 *       GITHUB_REPOSITORY: ${{ github.repository }}
 *       GITHUB_SHA: ${{ github.sha }}
 */

import * as fs from 'fs';
import * as path from 'path';
import { BuildBudget, toGitHubComment, toPrometheus } from '../src/index';
import { PersistenceManager } from '../src/persistence';
import { presetRules } from '../src/alerting';
import type { EntryMetrics } from '../src/types';

async function main() {
  const budget = new BuildBudget({ bloatThreshold: 0.15 });

  // Set alert rules
  budget.setAlertRules([
    presetRules.failOnLargeGrowth(),
    presetRules.warnTotalBundle500kb(),
    presetRules.warnConsecutiveGrowth(),
  ]);

  // Load persisted history
  const pm = new PersistenceManager({ filePath: './build-guardian-history.json' });
  await budget.loadHistory(pm);

  // Read build stats from file (generated by your build process)
  const statsPath = process.env.BUILD_STATS_PATH ?? './build-stats.json';
  if (!fs.existsSync(statsPath)) {
    console.log('No build stats found, skipping guardian check.');
    return;
  }

  const stats: { entries: EntryMetrics[] } = JSON.parse(fs.readFileSync(statsPath, 'utf-8'));

  for (const entry of stats.entries) {
    budget.recordEntry(entry);
  }

  const report = budget.finalizeBuild(`build-${process.env.GITHUB_SHA ?? Date.now()}`);

  // Output Prometheus metrics
  const promMetrics = toPrometheus(report);
  fs.writeFileSync('./build-guardian-metrics.txt', promMetrics);

  // Output GitHub PR comment
  const comment = toGitHubComment(report);
  fs.writeFileSync('./build-guardian-comment.md', comment);

  // Save history
  await budget.saveHistory(pm);

  // Post PR comment if in CI
  const githubToken = process.env.GITHUB_TOKEN;
  const prNumber = process.env.GITHUB_PR_NUMBER;
  const repo = process.env.GITHUB_REPOSITORY;

  if (githubToken && prNumber && repo) {
    console.log('Would post PR comment to GitHub.');
    // In a real implementation, use @actions/github or octokit:
    // await octokit.issues.createComment({ owner, repo, issue_number: prNumber, body: comment });
  }

  // Fail CI if needed
  const hasFailures = report.violations.length > 0 ||
    report.ruleAlerts.some((r) => r.rule.severity === 'fail');

  if (hasFailures) {
    console.error('❌ Build Guardian detected failures. Failing CI.');
    process.exit(1);
  }

  console.log('✅ Build Guardian check passed.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
